Feat/next
Spatial-Energy/spatial-energy.github.io pull request #1
Opened 2022-09-04 12:09 UTC by sabisin

Initial dev using next.js.

2022-09-07 16:45 UTC, grudelsud requested changes
thanks @sabisin 😄 I've added a few comments as discussed

2022-09-07 16:45 UTC, grudelsud commented on pages/_app.tsx
> +import React, { useEffect, useState } from "react";
can we please add the GA tag:

```<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WSLCVBQ8SE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WSLCVBQ8SE');
</script>```

2022-09-07 16:45 UTC, grudelsud commented on u9/components/Menu/Menu.tsx
> +const Menu = ({ ...props }: MenuProps) => {
I can't access the about and services pages when on mobile, is it possible to add the simplest possible menu to give access to such pages?

![localhost_3000_(Pixel 5)](https://user-images.githubusercontent.com/310976/188932799-aba9e513-cbc1-4b2e-945e-4bd1ab6bd57f.png)

2022-09-07 16:45 UTC, grudelsud commented on u9/containers/Services/Services.tsx
> +        phase: "Phase 3",
phase 3 and 4 come out as grey, both text and images. there's a "non greyed" version of such images in figma, can we please replace them, and have the text the same color of phase 1 and 2?

2022-09-07 16:45 UTC, grudelsud commented on u9/containers/About/About.tsx
> +            {data.map((item, index) => (
if it's not too much effort, can we have the same accordion as it's been implemented in the services page, please?

2022-09-10 14:00 UTC, sabisin commented
@grudelsud I have included the feedback. ✌️

2022-09-14 11:40 UTC, grudelsud approved these changes

2022-09-14 11:40 UTC, merged